disease:
  immunity:
    level: 1.0
    waning_rate: 1.0e-06
  name: plague
  outcome_rates_csv: ../../data/infection_outcome_rates_plague.csv
  settings:
    default_lowest_stage: exposed
    fatality_stage:
    - name: perished
    hospitalised_stage: []
    intensive_care_stage: []
    max_mild_symptom_tag: null
    recovered_stage:
    - name: recovered
    severe_symptoms_stay_at_home_stage:
    - name: primary_pneumonic
    stay_at_home_stage:
    - name: bacteraemia
  symptom_tags:
  - name: recovered
    value: -2
  - name: healthy
    value: -1
  - name: exposed
    value: 0
  - name: buboes_and_fever
    value: 2
  - name: bacteraemia
    value: 4
  - name: secondary_pneumonic
    value: 5
  - name: primary_pneumonic_onset
    value: 3
  - name: primary_pneumonic
    value: 6
  - name: perished
    value: 8
  trajectories:
  - description: 'Bubonic: exposed => buboes_and_fever => recovered'
    selection_key: bubonic_mild_recovered
    severity: 0.0
    stages:
    - completion_time:
        a: 2
        b: 5
        loc: 0.5
        scale: 12.0
        type: beta
      symptom_tag: exposed
    - completion_time:
        a: 2
        b: 5
        loc: 2.0
        scale: 4.0
        type: beta
      symptom_tag: buboes_and_fever
    - completion_time:
        type: constant
        value: 0.0
      symptom_tag: recovered
  - description: 'Bubonic: exposed => buboes_and_fever => bacteraemia => recovered'
    selection_key: bubonic_bacteraemia_recovered
    severity: 0.0
    stages:
    - completion_time:
        a: 2
        b: 5
        loc: 0.5
        scale: 12.0
        type: beta
      symptom_tag: exposed
    - completion_time:
        a: 2
        b: 5
        loc: 2.0
        scale: 2.0
        type: beta
      symptom_tag: buboes_and_fever
    - completion_time:
        loc: 0.0
        s: 0.24
        scale: 7.0
        type: lognormal
      symptom_tag: bacteraemia
    - completion_time:
        type: constant
        value: 0.0
      symptom_tag: recovered
  - description: 'Bubonic: exposed => buboes_and_fever => bacteraemia => perished'
    selection_key: bubonic_bacteraemia_perished
    severity: 0.0
    stages:
    - completion_time:
        a: 2
        b: 5
        loc: 0.5
        scale: 12.0
        type: beta
      symptom_tag: exposed
    - completion_time:
        a: 2
        b: 5
        loc: 2.0
        scale: 2.0
        type: beta
      symptom_tag: buboes_and_fever
    - completion_time:
        loc: 0.0
        s: 0.14
        scale: 4.0
        type: lognormal
      symptom_tag: bacteraemia
    - completion_time:
        type: constant
        value: 0.0
      symptom_tag: perished
  - description: 'Bubonic: exposed => buboes_and_fever => bacteraemia => secondary_pneumonic
      => perished'
    selection_key: bubonic_bacteraemia_pneumonic_death
    severity: 0.0
    stages:
    - completion_time:
        a: 2
        b: 5
        loc: 0.5
        scale: 12.0
        type: beta
      symptom_tag: exposed
    - completion_time:
        a: 2
        b: 5
        loc: 2.0
        scale: 2.0
        type: beta
      symptom_tag: buboes_and_fever
    - completion_time:
        type: constant
        value: 1
      symptom_tag: bacteraemia
    - completion_time:
        loc: 0.0
        s: 0.14
        scale: 4.0
        type: lognormal
      symptom_tag: secondary_pneumonic
    - completion_time:
        type: constant
        value: 0.0
      symptom_tag: perished
  - description: 'Pneumonic: exposed => primary_pneumonic => perished'
    selection_key: pneumonic_perished
    severity: 1.0
    stages:
    - completion_time:
        a: 2
        b: 5
        loc: 0.0
        scale: 5.0
        type: beta
      symptom_tag: exposed
    - completion_time:
        a: 2
        b: 2
        loc: 0.0
        scale: 1.5
        type: beta
      symptom_tag: primary_pneumonic_onset
    - completion_time:
        loc: 0.0
        s: 0.1
        scale: 1.8
        type: lognormal
      symptom_tag: primary_pneumonic
    - completion_time:
        type: constant
        value: 0.0
      symptom_tag: perished
  transmission:
    mode: Stage-Driven
    modes:
    - name: animal_bite
      susceptibility_multiplier: 2.0
    - name: respiratory
      susceptibility_multiplier: 2.0
    - deposition_stages:
        bacteraemia:
          type: constant
          value: 0.031067038883110628
        buboes_and_fever:
          end_value: 0.031067038883110628
          ramp_duration: 4.0
          start_value: 0.0
          type: linear_ramp
        primary_pneumonic:
          end_value: 0.031067038883110628
          ramp_duration: 4.0
          start_value: 0.0
          type: linear_ramp
        secondary_pneumonic:
          type: constant
          value: 0.031067038883110628
      fomite_curve:
        max_infectiousness: 0.01152824526073626
        mu: 2.59
        sigma: 0.8
        type: lognormal
      max_age: 21.0
      name: fomite
      susceptibility_multiplier: 2.0
      type: fomite
    stage_curves:
      animal_bite:
        bacteraemia:
          max_infectiousness: 0.09780543770561523
          rate: 0.6
          shape: 3.0
          shift: -0.5
          type: gamma
        buboes_and_fever:
          end_value: 0.048902718852807614
          ramp_duration: 4.0
          start_value: 0.0
          type: linear_ramp
        exposed:
          type: constant
          value: 0.0
        perished:
          type: constant
          value: 0.0
        primary_pneumonic:
          end_value: 0.08595454289670613
          ramp_duration: 1.0
          start_value: 0.01719090857934123
          type: linear_ramp
        primary_pneumonic_onset:
          end_value: 0.01719090857934123
          ramp_duration: 2.0
          start_value: 0.0
          type: linear_ramp
        recovered:
          type: constant
          value: 0.0
        secondary_pneumonic:
          type: constant
          value: 0.09780543770561523
      respiratory:
        bacteraemia:
          type: constant
          value: 0.0
        buboes_and_fever:
          type: constant
          value: 0.0
        exposed:
          type: constant
          value: 0.0
        perished:
          type: constant
          value: 0.0
        primary_pneumonic:
          type: constant
          value: 0.1233060864577036
        primary_pneumonic_onset:
          end_value: 0.1233060864577036
          ramp_duration: 1.5
          start_value: 0.0
          type: linear_ramp
        recovered:
          type: constant
          value: 0.0
        secondary_pneumonic:
          type: constant
          value: 4.164828800821533
