# Infection Seeding Configuration
# Controls how and when infections are introduced into the simulation

global_parameters:
  default_seed_past_infections: false
  default_seed_strength: 1.0
  base_cases_per_capita: 0.0002

# infection_seeds:
#   # Single uniform seeding event
#   - name: "basic_seeding"
#     type: "uniform"
#     date: "2024-01-01 08:00"
#     description: "Basic uniform seeding across entire simulation area"
#     parameters:
#       cases_per_capita_multiplier: 15.0
#       seed_past_infections: true

# infection_seeds:
#  - name: "attribute_and_geo_test"
#    type: "exact"
#    date: "2024-01-01 08:00"
#    geographic_cases:
#      level: "MBD_Temp_ID"
#      age_groups: ["18-30"]
#      units:
#        "TEMP003582": [10]
#       "TEMP005602": [10]

bulk_csv: "data/data_plague/bulk_seeds_plague.csv"
# config/bulk_seeds.csv"