enabled: false
vaccines:
  Pfizer:
    doses:
      - days_to_effective: 5
        days_to_waning: 6
        days_to_finished: 7
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.52
        symptom_efficacy:
          covid19: 
            "0-100": 0.52
      - days_to_effective: 7
        days_to_waning: 8
        days_to_finished: 9
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.95
        symptom_efficacy:
          covid19: 
            "0-100": 0.95
      - days_to_effective: 5
        days_to_waning: 6
        days_to_finished: 7
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.98
        symptom_efficacy:
          covid19: 
            "0-100": 0.98

  AstraZeneca:
    doses:
      - days_to_effective: 5
        days_to_waning: 6
        days_to_finished: 7
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.32
        symptom_efficacy:
          covid19: 
            "0-100": 0.32
      - days_to_effective: 7
        days_to_waning: 8
        days_to_finished: 9
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.75
        symptom_efficacy:
          covid19: 
            "0-100": 0.75
      - days_to_effective: 5
        days_to_waning: 6
        days_to_finished: 7
        waning_factor: 1.0
        infection_efficacy:
          covid19: 
            "0-100": 0.88
        symptom_efficacy:
          covid19: 
            "0-100": 0.88

campaigns:
  "Care Home Pfizer":
    start_date: "2024-01-01"
    end_date: "2024-01-20"
    days_to_next_dose: [0, 14]
    daily_coverage: 0.3
    vaccine_type: "Pfizer"
    dose_sequence: [0, 1]
    selection:
      - property: "activities.residence.venue_type"
        operator: "=="
        value: "care_home"

  "Care Home AstraZeneca":
    start_date: "2024-01-01"
    end_date: "2024-01-20"
    days_to_next_dose: [0, 14]
    daily_coverage: 0.3
    vaccine_type: "AstraZeneca"
    dose_sequence: [0, 1]
    selection:
      - property: "activities.residence.venue_type"
        operator: "=="
        value: "care_home"

  "Care Home Pfizer Booster":
    start_date: "2024-02-15"
    end_date: "2024-02-27"
    days_to_next_dose: [0]
    daily_coverage: 1.0
    vaccine_type: "Pfizer"
    dose_sequence: [2]
    last_dose_type_filter: ["Pfizer", "AstraZeneca"]
    selection:
      - property: "activities.residence.venue_type"
        operator: "=="
        value: "care_home"
